exam_app/urls.py
from django.urls import path
from .import views
urlpatterns=[
    path('dashboard', views.dashboard_view,name='dashboard'),
    path('exam', views.exam_view,name='exam'),
    path('add-exam', views.add_exam,name='add-exam'),
    path('view-exam', views.view_exam,name='view-exam'),
    path('delete-exam/<int:pk>', views.delete_exam,name='delete-exam'),


    path('question', views.question_view,name='question'),
    path('add-question', views.add_question,name='add-question'),
    path('view-question', views.view_question,name='view-question'),
    path('see-question/<int:pk>', views.see_question,name='see-question'),
    path('remove-question/<int:pk>', views.remove_question,name='remove-question'),
]
          
          

job_finder/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("users_app.urls")),
    path('company/',include("company_app.urls")),
    path('admin_app/',include("admin_app.urls")),
    path('',include("exam_app.urls")),
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users_app/models.py
from django.db import models
from django.contrib.auth.models import User
from company_app.models import JobList
from company_app.models import Employee
# Create your models here.



class JobApplication(models.Model):
    EXPERIENCE_CHOICES = [
        ('0-1', '0-1 years'),
        ('1-3', '1-3 years'),
        ('3-5', '3-5 years'),
        ('5+', '5+ years'),
    ]

    QUALIFICATION_CHOICES = [
        ('BSC', 'BSc'),
        ('BBA', 'BBA'),
        ('Btech', 'B.Tech'),
        ('MBA', 'MBA'),
        ('MCA', 'MCA'),
        ('MSC', 'MSC'),
        ('Mtech', 'M.Tech'),
        ('Diploma', 'Diploma'),
        ('ITI', 'ITI'),
        ('OTHER', 'Other'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    job = models.ForeignKey(JobList, on_delete=models.CASCADE)
    resume = models.FileField(upload_to='resumes/')
    profile_picture=models.ImageField(null=True,blank=True,upload_to="jobs")
    email = models.EmailField()
    location = models.CharField(max_length=255)
    contact = models.CharField(max_length=15)  # Adjust the max_length as needed
    qualification = models.CharField(max_length=20, choices=QUALIFICATION_CHOICES)
    experience = models.CharField(max_length=5, choices=EXPERIENCE_CHOICES)
    skills = models.TextField()
    application_date = models.DateTimeField(auto_now_add=True,null=True)

    def __str__(self):
        return f"{self.user.username} - {self.job.Job_name} Application"

   


class UserProfile(models.Model):
    user_ID = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True )
    User_Name = models.CharField(max_length=200,null=True,blank=True)
    Phone_Number = models.CharField(max_length=200,null=True,blank=True)
    Address = models.CharField(max_length=200,null=True,blank=True)
    Age = models.CharField(max_length=200,null=True,blank=True)
    User_photo = models.FileField(upload_to="users",null=True,blank=True)   


class Message(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    company=models.ForeignKey(Employee,on_delete=models.CASCADE,null=True,blank=True)
    added_Date = models.DateTimeField(auto_now=True)
    message = models.CharField(max_length=200,null=True,blank=True)
    reply = models.BooleanField(default=False)    

templates/company/add_exam.html
{%extends "company/company_joblist.html" %}
{%load static%}
{% load widget_tweaks %}
{% block content %}
<style>
  a:link {
        text-decoration: none;
      }
</style>
  
</head>
<h2 style="text-align:center; ">Add Course Info</h2>
<form method="POST" autocomplete="off" style="margin:100px;margin-top: 0px;">
    {%csrf_token%}
    <div class="form-group">
      <label for="course_name">Course Name</label>
      {% render_field courseForm.course_name class="form-control" placeholder="Example: Databases" %}

      <label for="question_number">Total Question</label>
      {% render_field courseForm.question_number class="form-control" placeholder="Example: 10" %}

      <label for="total_marks">Total Marks</label>
      {% render_field courseForm.total_marks class="form-control" placeholder="Example: 100" %}
    </div>
    <br><br>

    <button type="submit" class="btn btn-success" style="border-radius: 0%;">Submit Info</button>
    <input type="reset" class="btn btn-danger" style="border-radius: 0%;" placeholder="redet">
    <a href="{%url 'view-exam' %}" class="btn btn-primary">View questions</a>
  </form>
<br><br><br>
{% endblock content %}

templates/company/add_question.html
{%extends "company/company_joblist.html" %}
{%load static%}
{% load widget_tweaks %}
{% block content %}
<head>

  <style>

  a:link {
        text-decoration: none;
      }
    
  </style>
</head>
<h2 style="text-align:center;">Add Question</h2>
<form method="POST" autocomplete="off" style="margin:100px;margin-top: 0px;">
    {%csrf_token%}
    <div class="form-group">
        <label for="question">Course</label>
      {% render_field questionForm.courseID|attr:'required:true' class="form-control"  %}
        <br>

      <label for="question">Question</label>
      {% render_field questionForm.question|attr:'required:true' class="form-control" placeholder="Example: What is the relation calculus?" %}
        <br>
      <label for="question_number">Marks</label>
      {% render_field questionForm.marks|attr:'required:true' class="form-control" placeholder="Example: 5" %}
        <br>
      <label for="option1">Option 1</label>
      {% render_field questionForm.option1|attr:'required:true' class="form-control" placeholder="Example: It is a kind of procedural language" %}
        <br>
      <label for="option2">Option 2</label>
      {% render_field questionForm.option2|attr:'required:true' class="form-control" placeholder="Example: It is a non-procedural language" %}
        <br>
      <label for="option3">Option 3</label>
      {% render_field questionForm.option3|attr:'required:true' class="form-control" placeholder="Example: It is a high-level language" %}
        <br>
      <label for="option4">Option 4</label>
      {% render_field questionForm.option4|attr:'required:true' class="form-control" placeholder="Example: It is Data Definition language" %}
        <br>
      <label for="answer">Correct Answer</label>
      {% render_field questionForm.answer|attr:'required:true' class="form-control" %}
    </div>
    
<br>
    <button type="submit" class="btn btn-success" style="border-radius: 0%;">Submit Question</button>
  </form>
<br><br><br>
{% endblock content %}

templates/company/all_applications.html
{%extends "company/company_joblist.html" %}
{%load static%}
{%block content%}
<div class="container mt-4">
    <h1 class="mb-4">All Job Applications</h1>

    {% if all_applications %}
        <div class="row">
            {% for application in all_applications %}
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Job Title: {{ application.job.Job_name }}</h5>
                            <p class="card-text">
                                <strong style="color: rgb(9, 128, 86);">User:</strong> {{ application.user.username }}<br>
                                <strong style="color: rgb(42, 105, 82);">Contact Email:</strong> {{ application.email }}<br>
                                <strong style="color: rgb(42, 105, 82);">Qualification:</strong> {{ application.qualification }}<br>
                                <strong style="color: rgb(42, 105, 82);">Application Date:</strong> {{ application.application_date }}<br>
                                <strong style="color: rgb(42, 105, 82);">Resume:</strong>
                                {% if application.resume %}
                                    <a href="{{ application.resume.url }}" download="{{ application.resume.name }}">Download Resume</a>
                                    <!-- Alternatively, you can provide a link to view the resume -->
                                    <!-- <a href="{{ application.resume.url }}" target="_blank">View Resume</a> -->
                                {% else %}
                                    No resume uploaded
                                {% endif %}
                                <br><br>
                                <strong style="color: rgb(5, 28, 75);">
                                    <a href="{% url 'view_applicant' id=application.user.id %}">View Profile</a>
                                </strong>
                            </p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>No job applications found.</p>
    {% endif %}
</div>


{%endblock%}

templates/company/company_joblist.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>JobEntry - Job Portal Website Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{%static 'img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@700;800&display=swap" rel="stylesheet">
    
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{%static 'lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{%static 'lib/owlcarousel/assets/owl.carousel.min.css'%}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{%static 'css/bootstrap.min.css' %}" rel="stylesheet"> 

    <!-- Template Stylesheet -->
    <link href="{%static 'css/style.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <style>
        .pagination {
  display: inline-block;
}

.pagination a {
  color: black;
  float: left;
  padding: 8px 16px;
  text-decoration: none;
  transition: background-color .3s;
  border: 1px solid #ddd;
}

.pagination a.active {
  background-color: #4CAF50;
  color: white;
  border: 1px solid #4CAF50;
}

.pagination a:hover:not(.active) {background-color: #ddd;}
    </style>
</head>

<body>
    <div class="container-xxl bg-white p-0">
        <!-- Spinner Start -->
        <!-- <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div> -->
        <!-- Spinner End -->


        <!-- Navbar Start -->
        <nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-3">
            <a href="index.html" class="navbar-brand d-flex align-items-center text-center py-0 px-4 px-lg-5">
                <h1 class="m-0 text-primary">JobEntry</h1>
            </a>
            <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav ms-auto p-4 p-lg-0">
                    <a href="{%url 'home' %}" class="nav-item nav-link active">Home</a>
                    <a href="{%url 'company_job_list' %}" class="nav-item nav-link">Job List</a>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Assesment exam</a>
                        <div class="dropdown-menu rounded-0 m-0">
                            <a href="{%url 'add-exam' %}" class="dropdown-item">Add ExamCourse</a>
                            <a href="{%url 'add-question' %}" class="dropdown-item">Add Assesment</a>
                            <a href="{%url 'video_cam' %}" class="dropdown-item">Virtual meet</a>
                            
                        </div>
                    </div>
                    <a href="{%url 'employee_profile' %}" class="nav-item nav-link">Company Profile</a>
                    <a href="{%url 'all_applications' %}" class="nav-item nav-link">job Applications</a>
                </div>
                
               <a href="{%url 'company_signout' %}" class="nav-item nav-link" style="border-radius: 5px; background-color: #00B074; color: #fff; border: none;">Signout</a>
            </div>
        </nav>
        <!-- Navbar End -->
{% block content %}
<!-- Header End -->
<div class="container-xxl py-5 bg-dark page-header mb-5">
    <div class="container my-5 pt-5 pb-4">
        <h1 class="display-3 text-white mb-3 animated slideInDown">Job List</h1>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb text-uppercase">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item"><a href="#">Pages</a></li>
                <li class="breadcrumb-item text-white active" aria-current="page">Job List</li>
            </ol>
        </nav>
    </div>
</div>
<!-- Header End -->

<!-- Jobs Start -->
<div class="container-xxl py-5">
    <div class="container">
        <h1 class="text-center mb-5 wow fadeInUp" data-wow-delay="0.1s">Job Listing</h1>
        {%comment%}
        <!-- <div class="tab-class text-center wow fadeInUp" data-wow-delay="0.3s">
            <ul class="nav nav-pills d-inline-flex justify-content-center border-bottom mb-5">
                <li class="nav-item">
                    <a class="d-flex align-items-center text-start mx-3 ms-0 pb-3 active" data-bs-toggle="pill" href="#tab-1">
                        <h6 class="mt-n1 mb-0">Featured</h6>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="d-flex align-items-   center text-start mx-3 pb-3" data-bs-toggle="pill" href="#tab-2">
                        <h6 class="mt-n1 mb-0">Full Time</h6>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="d-flex align-items-center text-start mx-3 me-0 pb-3" data-bs-toggle="pill" href="#tab-3">
                        <h6 class="mt-n1 mb-0">Part Time</h6>
                    </a>
                </li>
            </ul>
        </div> -->
       {%endcomment%}
        <div class="tab-content">
            <div id="tab-1" class="tab-pane fade show p-0 active">
                <!-- Start of the loop -->
                {% for jobs in page_obj.object_list %}
                <div class="job-item p-4 mb-4">
                    <div class="row g-4">
                        <div class="col-sm-12 col-md-8 d-flex align-items-center">
                            <img class="flex-shrink-0 img-fluid border rounded" src="{{ jobs.Company_image.url }}" alt="" style="width: 80px; height: 80px;">
                            <div class="text-start ps-4">
                                <h5 class="mb-3">{{ jobs.Job_name }}</h5>
                                <span class="text-truncate me-3"><i class="fa fa-map-marker-alt text-primary me-2"></i>{{ jobs.Company_Location }}</span>
                                <span class="text-truncate me-3"><i class="far fa-clock text-primary me-2"></i>{{ jobs.Job_type }}</span>
                                <span class="text-truncate me-0"><i class="far fa-money-bill-alt text-primary me-2"></i>₹{{ jobs.Salary_range1 }}- ₹{{ jobs.Salary_range2 }}</span>
                            </div>
                        </div>
                        <div class="col-sm-12 col-md-4 d-flex flex-column align-items-start align-items-md-end justify-content-center">
                            <div class="d-flex mb-3">
                                <a class="btn btn-light btn-square me-3" href="{%url 'deletejob' jobs.Job_id %}"><i class="material-icons">delete</i></a>
                                <a class="btn btn-light btn-square me-3" href="{%url 'edit_job' jobs.Job_id %}"><i class='far fa-edit' style='font-size:24px'></i></a>
                                <a class="btn btn-primary" href="{%url 'company_job_details' jobs.Job_id %}">View job</a>
                                
                            </div>
                            <small class="text-truncate"><i class="far fa-calendar-alt text-primary me-2"></i>{{ jobs.published_date|date:"F d, Y"  }}</small>
                        </div>
                    </div>
                </div>
                {% endfor %}
                <div class="pagination-container d-flex justify-content-center">
                    {% if page_obj.has_previous %}
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
                    {% endif %}
                            <a class="page-link active" href="#">{{page_obj.number}}</a>
                    {% if page_obj.has_next %}
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
                    {% endif %}
                </div>
                
                
               
            </div>
            
        </div>
    </div>
</div>
<!-- Jobs End -->
{% endblock %}
      <!-- Footer Start -->
      <div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
        <div class="container py-5">
            <div class="row g-5">
                <div class="col-lg-3 col-md-6">
                    <h5 class="text-white mb-4">Company</h5>
                    <a class="btn btn-link text-white-50" href="">About Us</a>
                    <a class="btn btn-link text-white-50" href="">Contact Us</a>
                    <a class="btn btn-link text-white-50" href="">Our Services</a>
                    <a class="btn btn-link text-white-50" href="">Privacy Policy</a>
                    <a class="btn btn-link text-white-50" href="">Terms & Condition</a>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h5 class="text-white mb-4">Quick Links</h5>
                    <a class="btn btn-link text-white-50" href="">About Us</a>
                    <a class="btn btn-link text-white-50" href="">Contact Us</a>
                    <a class="btn btn-link text-white-50" href="">Our Services</a>
                    <a class="btn btn-link text-white-50" href="">Privacy Policy</a>
                    <a class="btn btn-link text-white-50" href="">Terms & Condition</a>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h5 class="text-white mb-4">Contact</h5>
                    <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>123 Street, New York, USA</p>
                    <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
                    <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@example.com</p>
                    <div class="d-flex pt-2">
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h5 class="text-white mb-4">Newsletter</h5>
                    <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>
                    <div class="position-relative mx-auto" style="max-width: 400px;">
                        <input class="form-control bg-transparent w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
                        <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="copyright">
                <div class="row">
                    <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                        &copy; <a class="border-bottom" href="#">Your Site Name</a>, All Right Reserved. 
                        
                        <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                        Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a>
                    </div>
                    <div class="col-md-6 text-center text-md-end">
                        <div class="footer-menu">
                            <a href="">Home</a>
                            <a href="">Cookies</a>
                            <a href="">Help</a>
                            <a href="">FQAs</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End -->


    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
</div>

<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="{%static 'lib/wow/wow.min.js' %}"></script>
<script src="{%static 'lib/easing/easing.min.js' %}"></script>
<script src="{%static 'lib/waypoints/waypoints.min.js' %}"></script>
<script src="{%static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

<!-- Template Javascript -->
<script src="{%static 'js/main.js' %}"></script>
</body>

</html>

templates/company/dashboard.html
{% load widget_tweaks %}
{% block content %}


<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <link href="http://netdna.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <style type="text/css">
      a:link {
        text-decoration: none;
      }
  
      .order-card {
        color: rgb(255, 255, 255);
      }
  
      .bg-c-blue {
        background: #04868f;
      }
  
      .bg-c-green {
        background:#4C51BF;
      }
  
      .bg-c-yellow {
        background: #F56565;
      }
  
      .bg-c-gtx {
        background:#57717d;
      }
  
  
      .card {
        
        -webkit-box-shadow: 0 1px 2.94px 0.06px rgba(4, 26, 55, 0.16);
        box-shadow: 0 1px 2.94px 0.06px rgba(4, 26, 55, 0.16);
        margin-bottom: 30px;
        -webkit-transition: all 0.3s ease-in-out;
        transition: all 0.3s ease-in-out;
      }
  
      .card .card-block {
        padding: 25px;
      }
  
      .order-card i {
        font-size: 26px;
      }
  
      .f-left {
        float: left;
      }
  
      .f-right {
        float: right;
      }
      header {
      left: 0px;
      right: 0px;
    }
    </style>
  </head>
<br><br>

  <div class="container">
    <div class="row">
      
        <div class="col-md-4 col-xl-4">
            <div class="card bg-c-gtx order-card">
              <div class="card-block">
                <h6 class="m-b-20">Registered Students </h6>
                <h2 class="text-right"><i class="fas fa-user-graduate f-left"></i><span>{{total_student}}</span></h2>
                
              </div>
            </div>
          </div>
  
      <div class="col-md-4 col-xl-4">
        <div class="card bg-c-yellow order-card">
          <div class="card-block">
            <h6 class="m-b-20">Total Courses</h6>
           <h2 class="text-right"><i class="fas fa-book f-left"></i><span>{{total_course}}</span></h2>
            
          </div>
        </div>
      </div>
  
      <div class="col-md-4 col-xl-4">
        <div class="card bg-c-blue order-card">
          <div class="card-block">
            <h6 class="m-b-20">Total Questions</h6>
            <h2 class="text-right"><i class="fas fa-question-circle f-left"></i><span>{{total_question}}</span></h2>
            
          </div>
        </div>
      </div>
    </div>
  </div>


<br>

<script src="http://netdna.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>


{% endblock content %}

templates/company/edit_job.html
{% extends "company/company_joblist.html" %}
{% load static %}

{% block content %}
<style>
    .form-container {
        margin-top: 5%;
        padding: 20px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        width: 50%; 
    }

    
    .form-group label {
        display: block;
        /* margin-bottom: 8px; */
    }

    
    .form-group input,
    .form-group textarea,
    .form-group select,
    .form-group input[type="file"] {
        width: 100%;
        padding: 5px;
        /* margin-bottom: 10px; */
        box-sizing: border-box;
        border-radius: 10px;
    }

  
    .text-center button {
        color: #fff;
        padding: 10px 20px;
        border: none;
        cursor: pointer;
    }

    .text-center button:hover {
        background-color: #0056b3;
    }
</style>

<div class="container form-container" data-aos="fade-up">
    <div class="section-header text-center">
        <h3>Edit Job</h3>
    </div>

    <form method="post" class="php-email-form" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            {{ form.as_p|safe }}
        </div>
        
        <div class="text-center mt-3">
            <button type="submit" class="btn btn-primary">Save Changes</button>
        </div>
    </form>
</div>
{% endblock %}

templates/company/see_question.html
{%extends "company/company_joblist.html" %}
{%load static%}
{% block content %}




  <style media="screen">
    a:link {
      text-decoration: none;
    }

    h6 {
      text-align: center;
    }

    .row {
      margin: 100px;
    }
  </style>
</head>
<br><br>
<div class="container">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h6 class="panel-title">Available Questions</h6>
    </div>
    <table class="table table-hover table-bordered" id="dev-table">
      <thead>
        <tr>

          <th>Question</th>
         
          <th>Marks</th>
          <th>Action</th>
        </tr>
      </thead>
      {% for c in questions %}
      <tr>

        <td> {{c.question}}</td>
        
        <td>{{c.marks}}</td>
        <td><a class="btn btn-danger btn-xs" style="border-radius: 0%;" href="{% url 'remove-question' c.id  %}"><span class="glyphicon glyphicon-trash"></span></a></td>
        
      </tr>
      {% endfor %}
    </table>
  </div>
</div>

<br><br><br><br><br><br>
{% endblock content %}

templates/company/view_application.html
{%block content%}
<div class="container mt-4">
    <h1 class="mb-4">Job Application Details</h1>

    <div class="card mb-4">
        <div class="card-body">
            <h5 class="card-title">Job Title: {{ user_application.job.Job_name }}</h5>
            <!-- Include other fields as needed -->
            <p class="card-text">
                <strong>User:</strong> {{ user_application.user.username }}<br>
                <strong>Email:</strong> {{ user_application.email }}<br>
                <strong>Location:</strong> {{ user_application.location }}<br>
                <strong>Contact:</strong> {{ user_application.contact }}<br>
                <strong>Qualification:</strong> {{ user_application.get_qualification_display }}<br>
                <strong>Experience:</strong> {{ user_application.get_experience_display }}<br>
                <strong>Skills:</strong> {{ user_application.skills }}<br>
                <strong>Application Date:</strong> {{ user_application.application_date }}<br>
            </p>
            <button><a href="{% url 'view_application' %}">Back to All Applications</a></button>
        </div>
    </div>
</div>
 
{%endblock%}